default_context:
  project_name: 'ChessDojo'
  project_slug: 'chessdojo'
  domain_main: 'chessdojo.com'
  domain_staging: 'stag.chessdojo.com'
  docker_swarm_stack_name_main: 'chessdojo-com'
  docker_swarm_stack_name_staging: 'stag-chessdojo-com'
  secret_key: 'e8b601d9f7997e542f9fdb86064a725f65e4720585d1ab199630f17ec16bc215'
  first_superuser: 'admin@chessdojo.com'
  first_superuser_password: 'e8b601d9f7997e542f9fdb86064a725f65e4720585d1ab199630f17ec16bc215'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.chessdojo.com", "https://stag.chessdojo.com", "https://chessdojo.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@chessdojo.com'
  postgres_password: 'e8b601d9f7997e542f9fdb86064a725f65e4720585d1ab199630f17ec16bc215'
  pgadmin_default_user: 'admin@chessdojo.com'
  pgadmin_default_user_password: 'e8b601d9f7997e542f9fdb86064a725f65e4720585d1ab199630f17ec16bc215'
  traefik_constraint_tag: 'chessdojo.com'
  traefik_constraint_tag_staging: 'stag.chessdojo.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:e8b601d9f7997e542f9fdb86064a725f65e4720585d1ab199630f17ec16bc215'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'pieterblomme/chessdojo-backend'
  docker_image_celeryworker: 'pieterblomme/chessdojo-celeryworker'
  docker_image_frontend: 'pieterblomme/chessdojo-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
